// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaKwDbwKBebXtrw0tUNi-nJ6GmkWXtPH8',
    appId: '1:588780355546:web:e86a60dd377c390dd24ae3',
    messagingSenderId: '588780355546',
    projectId: 'prueba-ii-moviles-iii',
    authDomain: 'prueba-ii-moviles-iii.firebaseapp.com',
    databaseURL: 'https://prueba-ii-moviles-iii-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-ii-moviles-iii.appspot.com',
    measurementId: 'G-Z88VH6C5ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ3UCGR7krOrFVODSQ_aF6CDOPJUi9tnY',
    appId: '1:588780355546:android:4abdab94388d2436d24ae3',
    messagingSenderId: '588780355546',
    projectId: 'prueba-ii-moviles-iii',
    databaseURL: 'https://prueba-ii-moviles-iii-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-ii-moviles-iii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClbKX3fcF843oWzSu7UVfxs9VFSgpzU1w',
    appId: '1:588780355546:ios:67336f21f0453dead24ae3',
    messagingSenderId: '588780355546',
    projectId: 'prueba-ii-moviles-iii',
    databaseURL: 'https://prueba-ii-moviles-iii-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-ii-moviles-iii.appspot.com',
    iosBundleId: 'com.example.prueba02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClbKX3fcF843oWzSu7UVfxs9VFSgpzU1w',
    appId: '1:588780355546:ios:67336f21f0453dead24ae3',
    messagingSenderId: '588780355546',
    projectId: 'prueba-ii-moviles-iii',
    databaseURL: 'https://prueba-ii-moviles-iii-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-ii-moviles-iii.appspot.com',
    iosBundleId: 'com.example.prueba02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaKwDbwKBebXtrw0tUNi-nJ6GmkWXtPH8',
    appId: '1:588780355546:web:da408b60bd71576dd24ae3',
    messagingSenderId: '588780355546',
    projectId: 'prueba-ii-moviles-iii',
    authDomain: 'prueba-ii-moviles-iii.firebaseapp.com',
    databaseURL: 'https://prueba-ii-moviles-iii-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-ii-moviles-iii.appspot.com',
    measurementId: 'G-DWJFMTXGMQ',
  );

}